### ISSUE TITLE
Just want to help ✋

### ISSUE THREAD

**Issue by benjaminhaeberli** [egrzeszczak/nuxt-3-notion#1]
Hi @egrzeszczak ! I found this repository yesterday while I was looking for a static rendering solution for Notion. I love this tool and would like to offer it as a CMS to my clients with small budgets. I would be glad to help you to implement missing components and improve the tool 😉

What I would find interesting in the future is that once all the components are integrated, it would be possible to create "themes". If Tailwind is well used, I think this can be done only by modifying the ``tailwind.config.js`` (fonts, colours, for example).

Thank you in advance!

**Comment by egrzeszczak** [comment]
Hello @benjaminhaeberli!
Thank you for your help, I'm planning to implement those components soon - right now I'm kinda busy with work. But if you have some spare time feel free to open a pull request :)

> What I would find interesting in the future is that once all the components are integrated, it would be possible to create "themes". If Tailwind is well used, I think this can be done only by modifying the tailwind.config.js (fonts, colours, for example).

As for themes, the project uses [DaisyUI](https://daisyui.com/), which has some themes already predefined. You can also to create your own theme and modify already existing ones. I highly suggest you check out [their documentation](https://daisyui.com/docs/themes/).

**Comment by benjaminhaeberli** [comment]
Thanks for your reply @egrzeszczak !

> Hello @benjaminhaeberli! Thank you for your help, I'm planning to implement those components soon - right now I'm kinda busy with work. But if you have some spare time feel free to open a pull request :)

Perfect ! I will try to work on it when I find some time (very busy with work too haha), I can't wait!

> As for themes, the project uses [DaisyUI](https://daisyui.com/), which has some themes already predefined. You can also to create your own theme and modify already existing ones. I highly suggest you check out [their documentation](https://daisyui.com/docs/themes/).

Nice ! I'll have a look at their docs, thanks 😉
